apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring-kotlin-microservice
spec:
  selector:
    matchLabels:
      app: sample-spring-kotlin-microservice
  template:
    metadata:
      labels:
        app: sample-spring-kotlin-microservice
      annotations:
        revision: "9bd9198f08692f9a8116a6b2bd61663da4f571a0"
        buildDate: "20211130131055"
    spec:
      containers:
      - name: sample-spring-kotlin-microservice
        image: localhost:5000/sample-spring-kotlin:1.4.0
        ports:
        - containerPort: 8080
