apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring-kotlin-microservice
spec:
  selector:
    matchLabels:
      app: sample-spring-kotlin-microservice
  template:
    metadata:
      labels:
        app: sample-spring-kotlin-microservice
    spec:
      containers:
      - name: sample-spring-kotlin-microservice
        image: localhost:5000/sample-spring-kotlin:1.4.0
        ports:
        - containerPort: 8080
